### ISSUE TITLE
Bien se préparer (En construction)

### ISSUE THREAD

**Issue by pasmax2** [ts-x/TSX-WEB#123]
# Code
```HTML
<ul>
  <li>Les Big Mac sont achetable au prêt d’un vendeur McDo ( Renvoie les dégâts pendant 5 secondes approximatif )</li>
  <li>Les Big Mac sont achetable au prêt d’un vendeur McDo ( Renvoie les dégâts pendant 5 secondes approximatif )</li>
</ul>
<span rp-item-information="54"></span><span rp-item-information="54"></span><span rp-item-information="54"></span>

<div class="text-center"><img class="img-circle" src="https://www.ts-x.eu/w/images/1/18/Artif.jpg" style="height: 120px; width: 120px" id="igmart"></div>
```
<ul>
  <li>Les Big Mac sont achetable au prêt d’un vendeur McDo ( Renvoie les dégâts pendant 5 secondes approximatif )</li>
  <li>Les Big Mac sont achetable au prêt d’un vendeur McDo ( Renvoie les dégâts pendant 5 secondes approximatif )</li>
</ul>
<div class="text-center"><img class="img-circle" src="https://www.ts-x.eu/w/images/1/18/Artif.jpg" style="height: 120px; width: 120px" id="igmart"></div>

![](http://image.prntscr.com/image/b8e135b27cb040cab5401f46c54be14c.jpeg)![](http://image.prntscr.com/image/b8e135b27cb040cab5401f46c54be14c.jpeg)

Mise en page presque fini et voila ce que ça l'aire à présent
![](http://image.prntscr.com/image/b5026a45a1e243a7a5636a0f40a403c6.jpeg)

# TODO

- [ ] - Mise en page
- [x] - Cherché les numéro ID des items
- [x] - Formulation des phrase
- [x] - Correction orthographique

# Bien se préparer
<div class="panel-body">
									<h3>La PVP</h3>
                                    <p>Vous voulez devenir expert en PVP, suffit de suivre ces instructions.
                                    Équipez-vous d’une Arme [PVP] (AK-47/M4A1-S/AWP...) à un Armurier.
                                    Quand vous aurez utilisé votre Arme [PVP] il vous faut également un San Andreas : Ce qui vous ajoutera 1000 balles dans votre chargeur ensuite utilisé une cartouche
                                    (incendiaires/empoisonnés/Paintball/explosive/vampirique) (Armurier/Artificier/Coach) ensuite il vous faut du stuff en supplément pour pouvoir survivre aux attaques ou même plus,
                                    <br />
                                    renvoyer les damages ou faire plus de damage. Grâce aux items suivants.</p>
                                    <br />
                                    <h3>Item obligatoire :</h3>
                                    <ul>
                                        <li>Les [PvP] drapeau son achetable au coach/mercenaire/sex-shop/banquier</li>
                                    </ul>
                                    <h3>Item optional :</h3>
                                    <ul>
                                        <li>Les Big Mac sont achetables au prêt d’un vendeur McDonald’s (renvoie les dégâts pendant 5secondes approximatif)</li>
                                        <li>Les Seringues du berserker sont achetables au prêt d’un membre de l’Hôpital (augmente les Dommages pendant 7-8 secondes approximatif)</li>
                                        <li>Les Cracks sont achetables au prêt d’un membre des dealers. (Réduction des dommages encaissés pendant 30 secondes Approximatif)</li>
                                        <li>Les Cocaïnes sont achetables au prêt d’un membre des dealers. (Vous donne 500 hp)
                                        Les Œils Bionique sont achetables au prêt d’un vendeur Technicien (annule l’effet visuel des drogues sur votre écran)</li>
                                        <li>Les Régénérations bioniques sont achetables au prêt d’un vendeur Technicien (augmente votre kevlar toutes les secondes)</li>
                                        <li>Les Kevlars + Casques sont achetable au prêt d’un vendeur Technicien/Préservatif sont achetable au prêt d’un vendeur sex-shop (vous augmente votre kevlar)</li>
                                        <li>Les Paires de baskets sont achetables au prêt d’un coach (réduis les dégâts de chutes)</li>
                                        <li>Les Propulseurs sont achetables au prêt d’un vendeur Technicien/Fusée sont achetable au prêt d’un artificier (Moyen le plus utile et rapide pour se déplacer en PVP)</li>
                                        <li>Amélioration précision de tir sont achetable au prêt d’un coach (augmente la précision de tir)</li>
                                        <li>Amélioration de toutes les capacités sont achetable au prêt d’un membre de l’hôpital (pack de chirurgie ce qui vous apporte comme bonus : vie/régent/saut/vitesse/force)</li>
                                        <br />
                                    </ul>
                                    <h3>Comment vous servire du [PVP] drapeau</h3>
                                    <p>Il vous faut également vous équiper de [PvP] drapeau, car l’objectif primaire est de capturer les zones en y jetant le drapeau à l’intérieur en appuyant sur la touche pour jeter votre arme.</p>
                                    <p>Pour utiliser le drapeau, il faut être à l’extérieur de la PVP. Sinon le drapeau ne s’activera pas et vous essayerez bêtement de marquer l’objectif, mais cela ne fonctionnera pas. Vous pourrez vous procurer les drapeaux dans les métiers suivants : (coach/mercenaire/sex-shop/banquier)</p>
								</div>

**Comment by pasmax2** [comment]
@messoremTsX  : Je pourrais avoir la liste des fonction dans ce style `rp-item-information="{{item.id}}"`

**Comment by kossolax** [comment]
C'est la seule, pour l'instant. Besoin d'une autre? Détail moi ce que tu
as besoin.

2016-11-22 1:16 GMT+01:00 DJBlack Phoénix <notifications@github.com>:

**Comment by pasmax2** [comment]
Je voudrais affiché chaque items comme dans les jobs mes un peu plus petit qui affiche la description au passage de la souri

**Comment by kossolax** [comment]
...


2016-11-22 8:20 GMT+01:00 DJBlack Phoénix <notifications@github.com>:

**Comment by pasmax2** [comment]
OK petit exemple

```
<span rp-item-information="114"></span>
<p>Les Big Mac sont achetable au prêt d’un vendeur McDo</p>
```

![](http://image.prntscr.com/image/b8e135b27cb040cab5401f46c54be14c.jpeg)
<span rp-item-information="114"></span>
<p>Les Big Mac sont achetable au prêt d’un vendeur McDo</p>

> Ce sont tout les items que nous conseillons à prendre pour faire des PVP mais je veux que l'image sois beaucoup plus petit

**Comment by kossolax** [comment]
Ça n'a pas grande utilité, mis à part alourdir le code derrière. Adapte
toi à comment elles sont. Tu peux écrire tout les conseils, et les items
sont affiché en bas de ton paragraphe.


 Blablalbla acheter des hamburgers vitaux au mcdo (1), blalbla des san
andreas (2) blablal une imprimante chez les tech (3) blalbal Lorem ipsum
dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

<span rp-item-information="114"></span><span
rp-item-information="114"></span><span
rp-item-information="114"></span><span
rp-item-information="114"></span>



Le 22 novembre 2016 à 08:31, DJBlack Phoénix <notifications@github.com> a
écrit :

**Comment by pasmax2** [comment]
:+1:

**Comment by pasmax2** [comment]
Je mais ça au propre et corrigé les faut d'orthographe et je push

**Comment by pasmax2** [comment]
Ce que ça l'aire à date pas tout à fais fini mais ça commence à prendre forme
![](http://image.prntscr.com/image/b5026a45a1e243a7a5636a0f40a403c6.jpeg)

**Comment by messoremTsX** [comment]
J'ai fait une rectif des descriptions items hier soir pour les affinés
niveaux effet.
Il sera donc possible de les intégrer oour diminuer le texte global et
faire moins "pavé".
Je suis dispo ts vers 21h30 si tu veux.

Le 24 nov. 2016 07:50, "DJBlack Phoénix" <notifications@github.com> a
écrit :

**Comment by pasmax2** [comment]
Ses good je serais la on regardera ça ensembles

**Comment by 0Gentleman** [comment]
Juste une question, comment fait-tu pour avoir un aperçu de ton code comme il sera sur la page ?
Genre voir https://camo.githubusercontent.com/c88cc0fe0e6939d5d2b3cc1c94882a6ce7d1e716/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f62353032366134356131653234336137613536333661306634306134303363362e6a706567
Alors qu'il n'est pas merged ?

**Comment by pasmax2** [comment]
Kossolax ma montré à faire avec la fonction inspecté sur le site tu édité
le code et t7 vois ce qui a l'aire

**Comment by pasmax2** [comment]
Voici une petit explication en image

![](http://image.prntscr.com/image/268f10b09bba4c1b8ebe90922f14f39c.jpeg)
![](http://image.prntscr.com/image/8713955648cf4756aeb280c014ce623c.jpeg)
![](http://image.prntscr.com/image/5cb99060ddde4005b561662dee1b01b3.jpeg)
![](http://image.prntscr.com/image/b7bdf6e4ccfd45528759a2e2e25fa1b8.jpeg)

**Comment by 0Gentleman** [comment]
Merci !

**Comment by pasmax2** [comment]
De rien l'ami

**Comment by pasmax2** [comment]
Première ébauche exemple jusque la reste encore un peu de travaille à faire mais ça commence à avoir de la gueule 
![](https://i.gyazo.com/ed9ff362256a1df31a75bd9e85427cc8.png)

**Comment by messoremTsX** [comment]
ça en est ou ?

**Comment by pasmax2** [comment]
faut que je fasse la mise au propre et voir si il manque rien et le mêtre
en place

:-) Black DJBlack :-)
Administrateur de Serveur créateur de site web Montage Photo et Vidéo et
homme à tout faire.

2017-01-06 15:35 GMT-05:00 Messorem <notifications@github.com>:

**Comment by pasmax2** [comment]
mise au propre terminé reste plus qu'a voir si tout va bien dans cet section je les push sur le github
